name: Export snapshot to Space
on:
  workflow_dispatch:
  push:
    branches:
      - feature/calendar-import

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create fresh repo and push
        env:
          HF_USER: ${{ secrets.HF_USER }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_URL: huggingface.co/spaces/vdyke/tmai-api-preview
          TARGET_BRANCH: main
        run: |
          rsync -av --exclude '.git' ./ ./_export/
          cd _export

          git init
          git config user.name  "github-actions[bot]"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Snapshot from ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
          git branch -M ${TARGET_BRANCH}
          git remote add origin https://${HF_USER}:${HF_TOKEN}@${SPACE_URL}
          git push -f origin ${TARGET_BRANCH}
